class RecipeConstants:
    MAX_COOKING_TIME = 720
    MIN_COOKING_TIME = 1
    MAX_RECIPE_NAME_LENGTH = 256
    MAX_RECIPE_TEXT_LENGTH = 2000


class IngredientConstants:
    MAX_INGREDIENT_AMOUNT = 100
    MIN_INGREDIENT_AMOUNT = 1
    MAX_INGREDIENT_NAME_LENGTH = 128
    MAX_MEASUREMENT_UNIT_LENGTH = 64


class UserConstants:
    MAX_EMAIL_LENGTH = 254
    MAX_FIRST_NAME_LENGTH = 150
    MAX_LAST_NAME_LENGTH = 150
    MAX_USERNAME_LENGTH = 150


class TagConstants:
    MAX_LENGTH = 32
